AWSTemplateFormatVersion: 2010-09-09
Description: |
This Cloudformation Template was written for running Kittens Carousel Static Website on EC2.
Kittens Carousel Static Website willbe deployed on Amazon Linux 2 (ami-0022f774911c1690) EC2 Instance with custom security group which aloows http connections on port 80 and ssh port on 22 from anywhere. Kittens Carousel Static Website is downloaded from Puclic Github repository, then deployed on Apache Web Server.
  
Resources:

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Enable HTTP for Apache Web Server and SSH for secure connection." # Required
      SecurityGroupIngress:
        - IpProtocol: TCP
          Fromport: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

        - IpProtocol: TCP
          Fromport: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0


  WebServerHost:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-0022f774911c1d690"
      InstanceType: "t2.micro"
      KeyName: "firstkey"
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      Tags:
        - Key: Name
          Value: Web Server Of ${AWS::StackName} Stack
      UserData:
        Fn::Base64: |
            #! /bin/bash
            yum update -y
            yum install httpd -y
            cd /var/www/html
            FOLDER="https://raw.githubusercontent.com/MEAKSOY/Projects/master/Project-101-Static-Web/static-web/"
            wget ${FOLDER}index.html
            wget ${FOLDER}cat0.jpg
            wget ${FOLDER}cat1.jpg
            wget ${FOLDER}cat2.jpg
            wget ${FOLDER}cat3.png
            systemctl start httpd
            systemctl enable httpd
  
Outputs: 
  WebsiteUrl: 
    Value: !Sub 
      - http://${PublicAddress}
      - PublicAdress: !GettAtt WebServerHost.PublicDnsName
    Description: Kitten Carousel Application URL